In [37]:
import numpy as np
import pandas as pd

In [38]:
data = pd.read_csv('cleaned_target.csv')

In [39]:
data.head()

,Unnamed: 0,PHSTAT_A,HYPMED_A,CHLMED_A,CHDEV_A,ANGEV_A,MIEV_A,STREV_A,ASEV_A,ASTILL_A,...,ASER12M_A,CANEV_A,DIBEV_A,COPDEV_A,ARTHEV_A,DEMENEV_A,ANXEV_A,DEPEV_A,AGEP_A,SHTFLU12M_A
0,0,3,NaN,2.0,2,2,2,2,2,NaN,...,NaN,2,2,2,2,2,2,2,97,2
1,1,1,NaN,NaN,2,2,2,2,2,NaN,...,NaN,2,2,2,2,2,2,2,28,2
2,2,3,1.0,1.0,2,2,2,2,2,NaN,...,NaN,1,2,2,1,2,2,2,72,1
3,3,2,1.0,NaN,2,2,2,2,2,NaN,...,NaN,2,2,2,1,2,2,2,60,2
4,4,4,1.0,1.0,1,1,1,2,1,1.0,...,2.0,2,1,1,2,2,1,1,60,1

In [40]:
data.shape

(31612, 21)

In [41]:
target = 'SHTFLU12M_A'
varnames = ['PHSTAT_A', 'HYPMED_A', 'CHLMED_A', 'CHDEV_A', 'ANGEV_A', 'MIEV_A', 'STREV_A', 'ASEV_A', 'ASTILL_A', 'ASAT12M_A', 'ASER12M_A', 'CANEV_A', 'DIBEV_A', 'COPDEV_A', 'ARTHEV_A', 'DEMENEV_A', 'ANXEV_A', 'DEPEV_A', 'AGEP_A']
#put these into a new dataframe
consolidated_data = pd.DataFrame(data[varnames])
consolidated_data['SHTFLU12M_A'] = data[target]
consolidated_data.columns

Index(['PHSTAT_A', 'HYPMED_A', 'CHLMED_A', 'CHDEV_A', 'ANGEV_A', 'MIEV_A',
       'STREV_A', 'ASEV_A', 'ASTILL_A', 'ASAT12M_A', 'ASER12M_A', 'CANEV_A',
       'DIBEV_A', 'COPDEV_A', 'ARTHEV_A', 'DEMENEV_A', 'ANXEV_A', 'DEPEV_A',
       'AGEP_A', 'SHTFLU12M_A'],
      dtype='object')

In [42]:
describe = consolidated_data.describe().T
describe

               count       mean        std   min   25%   50%   75%   max
PHSTAT_A     31612.0   2.407915   1.086598   1.0   2.0   2.0   3.0   9.0
HYPMED_A     11361.0   1.183875   0.444339   1.0   1.0   1.0   1.0   9.0
CHLMED_A      9103.0   1.342964   0.552582   1.0   1.0   1.0   2.0   9.0
CHDEV_A      31612.0   1.959762   0.416621   1.0   2.0   2.0   2.0   9.0
ANGEV_A      31612.0   1.994591   0.337096   1.0   2.0   2.0   2.0   9.0
MIEV_A       31612.0   1.967892   0.278079   1.0   2.0   2.0   2.0   9.0
STREV_A      31612.0   1.969157   0.280600   1.0   2.0   2.0   2.0   9.0
ASEV_A       31612.0   1.872896   0.387284   1.0   2.0   2.0   2.0   9.0
ASTILL_A      4191.0   1.429969   0.752275   1.0   1.0   1.0   2.0   9.0
ASAT12M_A     4191.0   1.758769   0.562791   1.0   1.0   2.0   2.0   9.0
ASER12M_A     4191.0   1.925555   0.330174   1.0   2.0   2.0   2.0   9.0
CANEV_A      31612.0   1.884443   0.370142   1.0   2.0   2.0   2.0   9.0
DIBEV_A      31612.0   1.900607   0.357572   1.0   2.0   2.0   2.0   9.0
COPDEV_A     31612.0   1.950019   0.298734   1.0   2.0   2.0   2.0   9.0
ARTHEV_A     31612.0   1.750095   0.492381   1.0   1.0   2.0   2.0   9.0
DEMENEV_A    31612.0   1.994116   0.203331   1.0   2.0   2.0   2.0   9.0
ANXEV_A      31612.0   1.858946   0.419165   1.0   2.0   2.0   2.0   9.0
DEPEV_A      31612.0   1.837973   0.443231   1.0   2.0   2.0   2.0   9.0
AGEP_A       31612.0  52.115083  18.441334  18.0  36.0  53.0  67.0  99.0
SHTFLU12M_A  31612.0   1.491870   0.499942   1.0   1.0   1.0   2.0   2.0

In [43]:
#check value counts for each variable in consolidated data
for c in consolidated_data.columns:
    print(c)
    print(consolidated_data[c].value_counts())

PHSTAT_A
2    10665
3     8782
1     7172
4     3732
5     1248
7        7
9        6
Name: PHSTAT_A, dtype: int64
HYPMED_A
1.0    9343
2.0    2007
9.0       8
7.0       3
Name: HYPMED_A, dtype: int64
CHLMED_A
1.0    6072
2.0    3018
9.0      13
Name: CHLMED_A, dtype: int64
CHDEV_A
2    29698
1     1829
9       66
7       19
Name: CHDEV_A, dtype: int64
ANGEV_A
2    30923
1      620
9       52
7       17
Name: ANGEV_A, dtype: int64
MIEV_A
2    30359
1     1219
9       17
7       17
Name: MIEV_A, dtype: int64
STREV_A
2    30389
1     1188
9       19
7       16
Name: STREV_A, dtype: int64
ASEV_A
2    27392
1     4191
7       15
9       14
Name: ASEV_A, dtype: int64
ASTILL_A
1.0    2557
2.0    1610
9.0      24
Name: ASTILL_A, dtype: int64
ASAT12M_A
2.0    3100
1.0    1081
9.0      10
Name: ASAT12M_A, dtype: int64
ASER12M_A
2.0    3855
1.0     333
9.0       3
Name: ASER12M_A, dtype: int64
CANEV_A
2    27771
1     3813
7       18
9       10
Name: CANEV_A, dtype: int64
DIBEV_A
2    28266
1     3316
7       18
9       12
Name: DIBEV_A, dtype: int64
COPDEV_A
2    29816
1     1765
7       16
9       15
Name: COPDEV_A, dtype: int64
ARTHEV_A
2    23438
1     8136
9       23
7       15
Name: ARTHEV_A, dtype: int64
DEMENEV_A
2    31240
1      345
7       15
9       12
Name: DEMENEV_A, dtype: int64
ANXEV_A
2    26869
1     4702
7       22
9       19
Name: ANXEV_A, dtype: int64
DEPEV_A
2    26180
1     5388
9       23
7       21
Name: DEPEV_A, dtype: int64
AGEP_A
85    1183
65     637
63     617
60     615
62     615
      ...
83     213
82     208
84     195
97      63
99       8
Name: AGEP_A, Length: 70, dtype: int64
SHTFLU12M_A
1    16063
2    15549
Name: SHTFLU12M_A, dtype: int64

PHSTAT_A: Would you say your health in general is excellent, very good, good, fair, or poor?
- 1 Excellent
- 2 Very Good
- 3 Good
- 4 Fair
- 5 Poor
- 7 Refused
- 9 Don't know

HYPMED_A: Were you told on two or more DIFFERENT visits that you had hypertension or high blood pressure?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

Sample Adults 18+ who were ever told they had hypertension

CHLMED_A: Are you NOW taking any medication prescribed by a doctor to help lower your cholesterol?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know
Sample Adults 18+ who were ever told they had high cholesterol

CHDEV_A: Have you EVER been told by a doctor or other health professional that you had ...Coronary heart disease?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

ANGEV_A: Have you EVER been told by a doctor or other health professional that you had
...Angina, also called angina pectoris?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

MIEV_A: Have you EVER been told by a doctor or other health professional that you had
...A heart attack, also called myocardial infarction?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

STREV_A: Have you EVER been told by a doctor or other health professional that you had
...A stroke?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

ASEV_A: Have you EVER been told by a doctor or other health professional that you had asthma?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

ASTILL_A: Do you still have asthma?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know
Sample Adults 18+ who were ever told they have asthma

ASAT12M_A: During the past 12 months, have you had an episode of asthma or an asthma attack?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know
Sample Adults 18+ who were ever told they had asthma
 
ASER12M_A: During the past 12 months, have you had to visit an emergency room or urgent care center because
of asthma?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know
Sample Adults 18+ who were ever told they had asthma

CANEV_A: Have you EVER been told by a doctor or other health professional that you had ...Cancer or a malignancy of any kind?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

DIBEV_A: Has a doctor or other health professional EVER told you that you had gestational diabetes, a
type of diabetes that occurs ONLY during pregnancy?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know
Female Sample Adults 18+

COPDEV_A: Have you EVER been told by a doctor or other health professional that you had ...Chronic Obstructive Pulmonary Disease, C.O.P.D., emphysema, or chronic bronchitis?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

ARTHEV_A: Have you EVER been told by a doctor or other health professional that you had
...Some form of arthritis, rheumatoid arthritis, gout, lupus, or fibromyalgia
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

DEMENEV_A: Have you EVER been told by a doctor or other health professional that you had
...Dementia, including Alzheimer's disease?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

ANXEV_A: Any type of anxiety disorder?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

DEPEV_A: Any type of depression?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

AGEP_A: couldn't find in codebook but it's the age of the participant

target: There are two types of flu vaccinations. One is a shot and the other is a spray, mist, or drop in the nose. During the past 12 months, have you had a flu vaccination?
- 1 Yes
- 2 No
- 7 Refused
- 9 don't know

In [44]:
#chi squared before imputing
#chi squared test for feature and target
#need the frequencies for the values
from scipy.stats import chi2_contingency

def chi(data, target):

    for c in data.columns:
        print(c)
        data_crosstab = pd.crosstab(data[c], 
                                    target,  
                                       margins = False) 
        stat, p, dof, expected = chi2_contingency(data_crosstab)
        # select significance value

        alpha = 0.05
        # Determine whether to reject or keep your null hypothesis
        print(alpha, p)
        if p <= alpha:
            print('Variables are associated (reject H0)')
        else:
            print('Variables are not associated(fail to reject H0)')

In [45]:
chi(consolidated_data, consolidated_data['SHTFLU12M_A'])

PHSTAT_A
0.05 1.730877103275288e-33
Variables are associated (reject H0)
HYPMED_A
0.05 6.006745975544979e-82
Variables are associated (reject H0)
CHLMED_A
0.05 2.562471075029095e-79
Variables are associated (reject H0)
CHDEV_A
0.05 7.6445024083022615e-87
Variables are associated (reject H0)
ANGEV_A
0.05 1.793784479932828e-14
Variables are associated (reject H0)
MIEV_A
0.05 1.0869464916436795e-24
Variables are associated (reject H0)
STREV_A
0.05 4.256778682898849e-20
Variables are associated (reject H0)
ASEV_A
0.05 3.112990516222618e-06
Variables are associated (reject H0)
ASTILL_A
0.05 1.900281608839181e-05
Variables are associated (reject H0)
ASAT12M_A
0.05 0.31644711161888744
Variables are not associated(fail to reject H0)
ASER12M_A
0.05 0.13082230462904124
Variables are not associated(fail to reject H0)
CANEV_A
0.05 3.797951202233885e-116
Variables are associated (reject H0)
DIBEV_A
0.05 5.220254463560871e-89
Variables are associated (reject H0)
COPDEV_A
0.05 2.9050770282582474e-38
Variables are associated (reject H0)
ARTHEV_A
0.05 6.21430914774778e-169
Variables are associated (reject H0)
DEMENEV_A
0.05 7.464395122252592e-13
Variables are associated (reject H0)
ANXEV_A
0.05 1.0760959777176732e-08
Variables are associated (reject H0)
DEPEV_A
0.05 2.7223992302067546e-13
Variables are associated (reject H0)
AGEP_A
0.05 0.0
Variables are associated (reject H0)
SHTFLU12M_A
0.05 0.0
Variables are associated (reject H0)

In [46]:
#impute values with 2 for the questions that were only asked to people who answered "yes" to other questions
#make list of columns that make sense to do this
impute = ['HYPMED_A', 'CHLMED_A', 'ASTILL_A', 'ASAT12M_A', 'ASER12M_A', 'DIBEV_A']
for col in impute:
    mask = pd.isnull(consolidated_data[col])
    consolidated_data[col][mask == True] = 2

<ipython-input-46-707d1d739d5a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  consolidated_data[col][mask == True] = 2

In [47]:
consolidated_data.describe()

,PHSTAT_A,HYPMED_A,CHLMED_A,CHDEV_A,ANGEV_A,MIEV_A,STREV_A,ASEV_A,ASTILL_A,ASAT12M_A,ASER12M_A,CANEV_A,DIBEV_A,COPDEV_A,ARTHEV_A,DEMENEV_A,ANXEV_A,DEPEV_A,AGEP_A,SHTFLU12M_A
count,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.00000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000,31612.000000
mean,2.407915,1.706694,1.810800,1.959762,1.994591,1.967892,1.969157,1.872896,1.924427,1.968018,1.99013,1.884443,1.900607,1.950019,1.750095,1.994116,1.858946,1.837973,52.115083,1.491870
std,1.086598,0.473607,0.420046,0.416621,0.337096,0.278079,0.280600,0.387284,0.335232,0.220624,0.12283,0.370142,0.357572,0.298734,0.492381,0.203331,0.419165,0.443231,18.441334,0.499942
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,18.000000,1.000000
25%,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,36.000000,1.000000
50%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,53.000000,1.000000
75%,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,67.000000,2.000000
max,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,99.000000,2.000000

In [48]:
consolidated_data.isnull().sum()

PHSTAT_A       0
HYPMED_A       0
CHLMED_A       0
CHDEV_A        0
ANGEV_A        0
MIEV_A         0
STREV_A        0
ASEV_A         0
ASTILL_A       0
ASAT12M_A      0
ASER12M_A      0
CANEV_A        0
DIBEV_A        0
COPDEV_A       0
ARTHEV_A       0
DEMENEV_A      0
ANXEV_A        0
DEPEV_A        0
AGEP_A         0
SHTFLU12M_A    0
dtype: int64

In [49]:
describe

               count       mean        std   min   25%   50%   75%   max
PHSTAT_A     31612.0   2.407915   1.086598   1.0   2.0   2.0   3.0   9.0
HYPMED_A     11361.0   1.183875   0.444339   1.0   1.0   1.0   1.0   9.0
CHLMED_A      9103.0   1.342964   0.552582   1.0   1.0   1.0   2.0   9.0
CHDEV_A      31612.0   1.959762   0.416621   1.0   2.0   2.0   2.0   9.0
ANGEV_A      31612.0   1.994591   0.337096   1.0   2.0   2.0   2.0   9.0
MIEV_A       31612.0   1.967892   0.278079   1.0   2.0   2.0   2.0   9.0
STREV_A      31612.0   1.969157   0.280600   1.0   2.0   2.0   2.0   9.0
ASEV_A       31612.0   1.872896   0.387284   1.0   2.0   2.0   2.0   9.0
ASTILL_A      4191.0   1.429969   0.752275   1.0   1.0   1.0   2.0   9.0
ASAT12M_A     4191.0   1.758769   0.562791   1.0   1.0   2.0   2.0   9.0
ASER12M_A     4191.0   1.925555   0.330174   1.0   2.0   2.0   2.0   9.0
CANEV_A      31612.0   1.884443   0.370142   1.0   2.0   2.0   2.0   9.0
DIBEV_A      31612.0   1.900607   0.357572   1.0   2.0   2.0   2.0   9.0
COPDEV_A     31612.0   1.950019   0.298734   1.0   2.0   2.0   2.0   9.0
ARTHEV_A     31612.0   1.750095   0.492381   1.0   1.0   2.0   2.0   9.0
DEMENEV_A    31612.0   1.994116   0.203331   1.0   2.0   2.0   2.0   9.0
ANXEV_A      31612.0   1.858946   0.419165   1.0   2.0   2.0   2.0   9.0
DEPEV_A      31612.0   1.837973   0.443231   1.0   2.0   2.0   2.0   9.0
AGEP_A       31612.0  52.115083  18.441334  18.0  36.0  53.0  67.0  99.0
SHTFLU12M_A  31612.0   1.491870   0.499942   1.0   1.0   1.0   2.0   2.0

In [50]:
#want to check the percentage of data of each feature that is not 1 or 2 (these are the major answers for each question--yes/no)
p = .1
newcols = pd.DataFrame()
for i in range(len(consolidated_data.columns)):
    col = consolidated_data.columns[i]
    index_vals = list(consolidated_data[col].value_counts().index)
    vals = [consolidated_data[col].value_counts()[index_vals[j]] for j in range(len(index_vals)) if index_vals[j] != 1 and index_vals[j] != 2]
    ind = [index_vals[j] for j in range(len(index_vals)) if index_vals[j] != 1 and index_vals[j] != 2]
    percentage = sum(vals)/len(consolidated_data)
    print(ind)
    #Binning non yes/no values if the percentage is less than 10
    if percentage < p:
        index = []
        for k in range(len(ind)):
            index.append(list(np.where(consolidated_data[col] == ind[k])))
            t = pd.DataFrame(index)
            consolidated_data[col].loc[t[0][k]] = 10

[3, 4, 5, 7, 9]
[9.0, 7.0]
[9.0]
[9, 7]
[9, 7]
[9, 7]
[9, 7]
[7, 9]
[9.0]
[9.0]
[9.0]
[7, 9]
[7, 9]
[7, 9]
[9, 7]
[7, 9]
[7, 9]
[9, 7]
[85, 65, 63, 60, 62, 66, 61, 59, 55, 54, 64, 69, 70, 58, 72, 68, 71, 34, 36, 28, 56, 39, 67, 31, 57, 33, 38, 37, 50, 32, 35, 43, 29, 30, 48, 53, 40, 52, 42, 44, 47, 41, 46, 51, 45, 49, 26, 27, 73, 25, 76, 23, 24, 74, 75, 77, 22, 78, 21, 20, 18, 80, 79, 19, 81, 83, 82, 84, 97, 99]
[]

/Users/saraokun/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [51]:
col = consolidated_data.columns

In [52]:
for i in range(len(col)):
    print(consolidated_data[col[i]].value_counts())

2    10665
3     8782
1     7172
4     3732
5     1248
7        7
9        6
Name: PHSTAT_A, dtype: int64
2.0     22258
1.0      9343
10.0       11
Name: HYPMED_A, dtype: int64
2.0     25527
1.0      6072
10.0       13
Name: CHLMED_A, dtype: int64
2     29698
1      1829
10       85
Name: CHDEV_A, dtype: int64
2     30923
1       620
10       69
Name: ANGEV_A, dtype: int64
2     30359
1      1219
10       34
Name: MIEV_A, dtype: int64
2     30389
1      1188
10       35
Name: STREV_A, dtype: int64
2     27392
1      4191
10       29
Name: ASEV_A, dtype: int64
2.0     29031
1.0      2557
10.0       24
Name: ASTILL_A, dtype: int64
2.0     30521
1.0      1081
10.0       10
Name: ASAT12M_A, dtype: int64
2.0     31276
1.0       333
10.0        3
Name: ASER12M_A, dtype: int64
2     27771
1      3813
10       28
Name: CANEV_A, dtype: int64
2     28266
1      3316
10       30
Name: DIBEV_A, dtype: int64
2     29816
1      1765
10       31
Name: COPDEV_A, dtype: int64
2     23438
1      8136
10       38
Name: ARTHEV_A, dtype: int64
2     31240
1       345
10       27
Name: DEMENEV_A, dtype: int64
2     26869
1      4702
10       41
Name: ANXEV_A, dtype: int64
2     26180
1      5388
10       44
Name: DEPEV_A, dtype: int64
85    1183
65     637
63     617
60     615
62     615
      ...
83     213
82     208
84     195
97      63
99       8
Name: AGEP_A, Length: 70, dtype: int64
1    16063
2    15549
Name: SHTFLU12M_A, dtype: int64

In [53]:
chi(consolidated_data, consolidated_data['SHTFLU12M_A'])

PHSTAT_A
0.05 1.730877103275288e-33
Variables are associated (reject H0)
HYPMED_A
0.05 1.0453991928278857e-282
Variables are associated (reject H0)
CHLMED_A
0.05 1.838659295250508e-291
Variables are associated (reject H0)
CHDEV_A
0.05 2.097792970874963e-87
Variables are associated (reject H0)
ANGEV_A
0.05 6.263516412755908e-15
Variables are associated (reject H0)
MIEV_A
0.05 1.5959801315271718e-25
Variables are associated (reject H0)
STREV_A
0.05 5.46912226522728e-21
Variables are associated (reject H0)
ASEV_A
0.05 8.565983422125263e-07
Variables are associated (reject H0)
ASTILL_A
0.05 7.050239692968778e-11
Variables are associated (reject H0)
ASAT12M_A
0.05 0.0009044545677365537
Variables are associated (reject H0)
ASER12M_A
0.05 0.009945050532951851
Variables are associated (reject H0)
CANEV_A
0.05 7.116477708985938e-117
Variables are associated (reject H0)
DIBEV_A
0.05 5.542382032007576e-90
Variables are associated (reject H0)
COPDEV_A
0.05 4.005838157893319e-39
Variables are associated (reject H0)
ARTHEV_A
0.05 3.1112213920386854e-170
Variables are associated (reject H0)
DEMENEV_A
0.05 1.8676768471593722e-13
Variables are associated (reject H0)
ANXEV_A
0.05 2.6655122301187886e-09
Variables are associated (reject H0)
DEPEV_A
0.05 4.290213997930653e-14
Variables are associated (reject H0)
AGEP_A
0.05 0.0
Variables are associated (reject H0)
SHTFLU12M_A
0.05 0.0
Variables are associated (reject H0)

In [54]:
consolidated_data.to_csv('sara_cleaned_features_test2.csv')